name: example-environment 
channels:
  - conda-forge
  - defaults
dependencies:
  - ruby
  - python
  - numpy=1.15.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets
  - widgetsnbextension
  - RISE
  - python-igraph=0.7.1
  - igraph
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas=0.23.4
    - matplotlib
    - pathlib
    - MulticoreTSNE
    - scikit-learn=0.19.2
    - scipy=1.1.0
    - statsmodels=0.9.0
    - scanpy=1.1
    - louvain==0.6.1 
    - anndata=0.6.4
    - jupyter-wysiwyg
