name: example-environment 
channels:
  - conda-forge
  - ruby
  - defaults
dependencies:
  - python
  - numpy==1.13.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets
  - widgetsnbextension
  - RISE
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas==0.22.0
    - matplotlib
    - pathlib
    - MulticoreTSNE
    - scanpy==1.1
    - python-igraph
    - louvain==0.6.1
    - anndata==0.6.4
    - jupyter-wysiwyg
