name: example-environment 
channels:
  - conda-forge
  - ruby
  - defaults
dependencies:
  - python
  - numpy==1.13.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets
  - widgetsnbextension
  - RISE
  - python-igraph
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas==0.22.0
    - matplotlib
    - pathlib
    - MulticoreTSNE
    - scanpy==1.1
    - louvain==0.6.1
    - anndata==0.6.4
    - jupyter-wysiwyg
presentation:
  - postBuild:
    jupyter nbextension install calysto --user
    jupyter nbextension enable calysto/document-tools/main
    jupyter nbextension enable calysto/cell-tools/main
    jupyter nbextension enable calysto/spell-check/main
    jupyter nbextension enable calysto/publish/main
    jupyter nbextension enable calysto/submit/main
    jupyter nbextension enable calysto/annotate/main
    jupyter nbextension enable --py widgetsnbextension
    jupyter nbextension enable python-markdown/main
# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
    jupyter trust 2datasets-analysis.ipynb
    jupyter trust 2datasets_individually-seurat.ipynb

