name: example-environment 
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - RISE
  - python-igraph
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - pathlib
    - MulticoreTSNE
    - scanpy==1.1
    - anndata==0.6.4
    - louvain==0.6.1
    - jupyter-wysiwyg
